# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Layman
                                 A QGIS plugin
 Layman
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-02-15
        copyright            : (C) 2019 by jan vrobel
        email                : vrobel.jan@seznam.cz
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import os
import pathlib
import sys
src_dir = pathlib.Path(__file__).parent.resolve()

libqfieldsync_whl = src_dir / "libqfieldsync.whl"
if libqfieldsync_whl.exists():
    sys.path.append(str(libqfieldsync_whl))

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Layman class from file Layman.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Layman import Layman
    return Layman(iface)


