# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CartoDBDialog
                                 A QGIS plugin
 CartoDB plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-03-19
        git sha              : $Format:%H$
        copyright            : (C) 2019 by Jan Vrobel
        email                : vrobel.jan@seznam.cz
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import io
import configparser

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
import requests, json
from qgis.PyQt.QtGui import QCursor
from qgis.PyQt.QtCore import Qt

from .layman_utils import LaymanUtils
from .layman_utils import ProxyStyle
import tempfile
import shutil
from qgis.PyQt.QtWidgets import QMessageBox
from zipfile import ZipFile
from qgis.core import Qgis
from .layman_api import LaymanAPI

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(os.path.dirname(__file__), "dlg_userInfo.ui")
)


class UserInfoDialog(QtWidgets.QDialog, FORM_CLASS):
    MASTER_URL = "https://github.com/LESPROJEKT/qgis-layman-plugin/archive/master.zip"
    BRANCH_3_0_URL = (
        "https://github.com/LESPROJEKT/qgis-layman-plugin/archive/refs/heads/3.x.zip"
    )

    def __init__(
        self,
        utils,
        iface,
        isAuthorized,
        server,
        laymanUsername,
        URI,
        laymanVersion,
        layman,
        parent=None,
    ):
        """Constructor."""
        super(UserInfoDialog, self).__init__(parent)
        self.setupUi(self)
        self.iface = iface
        self.isAuthorized = isAuthorized
        self.server = server
        self.laymanUsername = laymanUsername
        self.utils = utils
        self.URI = URI
        self.laymanVersion = laymanVersion
        app = QtWidgets.QApplication.instance()
        proxy_style = ProxyStyle(app.style())
        self.layman = layman
        self.setStyle(proxy_style)
        if URI:
            self.layman_api = LaymanAPI(URI)
        self.setUi()

    def setUi(self):
        self.utils.recalculateDPI()
        self.setStyleSheet("#DialogBase {background: #f0f0f0 ;}")
        self.comboBox_port.addItem("7070")
        self.comboBox_port.addItem("7071")
        self.comboBox_port.addItem("7072")
        port = self.utils.getConfigItem("port")
        if self.layman.qfieldReady:
            self.label_qfield_server.setText("Ready")
        else:
            self.label_qfield_server.setText("Not available")
        if not port:
            self.comboBox_port.setCurrentIndex(0)
            self.layman.port = "7070"
        else:
            if port == "7070":
                self.layman.port = "7070"
                self.comboBox_port.setCurrentIndex(0)
            elif port == "7071":
                self.layman.port = "7071"
                self.comboBox_port.setCurrentIndex(1)
            elif port == "7072":
                self.layman.port = "7072"
                self.comboBox_port.setCurrentIndex(2)
        self.comboBox_port.currentIndexChanged.connect(self.utils.setPortValue)

        current_version = self.utils.getVersion()
        version_parts = current_version.split(".")

        if len(version_parts) >= 2 and int(version_parts[0]) >= 3:
            self.pushButton_update.setText(self.tr("Update"))
            self.pushButton_update.clicked.connect(
                lambda: self.updatePlugin(self.BRANCH_3_0_URL)
            )
            self.pushButton_upgrade_downgrade.setText(self.tr("Downgrade"))
            self.pushButton_upgrade_downgrade.clicked.connect(
                lambda: self.upgradeDowngradePlugin(self.MASTER_URL, "downgrade")
            )
        else:
            self.pushButton_update.setText(self.tr("Update"))
            self.pushButton_update.clicked.connect(
                lambda: self.updatePlugin(self.MASTER_URL)
            )
            self.pushButton_upgrade_downgrade.setText(self.tr("Upgrade"))
            self.pushButton_upgrade_downgrade.clicked.connect(
                lambda: self.upgradeDowngradePlugin(self.BRANCH_3_0_URL, "upgrade")
            )

        if self.server != None and self.laymanUsername != "":
            userEndpoint = self.layman_api.get_current_user_url()
            r = self.utils.requestWrapper("GET", userEndpoint, payload=None, files=None)
            res = r.text
            res = self.utils.fromByteToJson(r.content)

            # Check version availability based on current plugin version
            if len(version_parts) >= 2 and int(version_parts[0]) >= 3:
                # For 3.x versions, check 3.x branch
                versionCheck = self.checkVersionForBranch("3.x")
            else:
                # For 2.x versions, check master branch
                versionCheck = self.checkVersionForBranch("master")

            if self.isAuthorized:
                self.label_layman.setText(res["username"])
                self.label_agrihub.setText(res["claims"]["email"])
                self.pushButton_delete_user.clicked.connect(self.delete_whole_user)
            else:
                self.label_layman.setText("Anonymous")
            self.label_server.setText(self.server)

            self.setStyleSheet("#DialogBase {background: #f0f0f0 ;}")
            self.label_version.setText(self.utils.getVersion())
            self.label_versionLayman.setText(self.laymanVersion)
            self.pushButton_close.clicked.connect(lambda: self.close())

            self.label_avversion.setText(versionCheck[1])
            if versionCheck[0] == True:
                self.pushButton_update.setEnabled(False)
        else:
            self.label_version.setText(self.utils.getVersion())
            if len(version_parts) >= 2 and int(version_parts[0]) >= 3:
                versionCheck = self.checkVersionForBranch("3.x")
            else:
                versionCheck = self.checkVersionForBranch("master")

            self.label_avversion.setText(versionCheck[1])
            if versionCheck[0] == True:
                self.pushButton_update.setEnabled(False)
        self.pushButton_close.clicked.connect(lambda: self.close())

    def upgradeDowngradePlugin(self, url, action_type):
        current_version = self.utils.getVersion()
        version_parts = current_version.split(".")

        if not self.checkQgisVersion():
            msgbox = QMessageBox(
                QMessageBox.Icon.Question,
                self.tr("Plugin update"),
                self.tr(
                    "Plugin requires QGIS version 3.26 and higher. Do you still want to continue?"
                ),
            )
            msgbox.addButton(QMessageBox.StandardButton.Yes)
            msgbox.addButton(QMessageBox.StandardButton.No)
            msgbox.setDefaultButton(QMessageBox.StandardButton.No)
            reply = msgbox.exec()
            if reply == QMessageBox.StandardButton.No:
                return

        if action_type == "downgrade":
            msgbox = QMessageBox(
                QMessageBox.Icon.Question,
                self.tr("Plugin downgrade"),
                self.tr(
                    f"Do you want to downgrade the plugin from version {current_version} to version 2.x?"
                ),
            )
        else:
            msgbox = QMessageBox(
                QMessageBox.Icon.Question,
                self.tr("Plugin upgrade"),
                self.tr(
                    f"Do you want to upgrade the plugin from version {current_version} to version 3.x?"
                ),
            )

        msgbox.addButton(QMessageBox.StandardButton.Yes)
        msgbox.addButton(QMessageBox.StandardButton.No)
        msgbox.setDefaultButton(QMessageBox.StandardButton.No)
        reply = msgbox.exec()
        if reply == QMessageBox.StandardButton.No:
            return

        self.installPlugin(url, action_type)

    def updatePlugin(self, url):
        current_version = self.utils.getVersion()
        version_parts = current_version.split(".")

        if not self.checkQgisVersion():
            msgbox = QMessageBox(
                QMessageBox.Icon.Question,
                self.tr("Plugin update"),
                self.tr(
                    "Plugin requires QGIS version 3.26 and higher. Do you still want to continue?"
                ),
            )
            msgbox.addButton(QMessageBox.StandardButton.Yes)
            msgbox.addButton(QMessageBox.StandardButton.No)
            msgbox.setDefaultButton(QMessageBox.StandardButton.No)
            reply = msgbox.exec()
            if reply == QMessageBox.StandardButton.No:
                return

        if len(version_parts) >= 2 and int(version_parts[0]) >= 3:
            msgbox = QMessageBox(
                QMessageBox.Icon.Question,
                self.tr("Plugin update"),
                self.tr(
                    f"Do you want to update the plugin version {current_version} (3.x)?"
                ),
            )
        else:
            msgbox = QMessageBox(
                QMessageBox.Icon.Question,
                self.tr("Plugin update"),
                self.tr(
                    f"Do you want to update the plugin version {current_version} (2.x)?"
                ),
            )

        msgbox.addButton(QMessageBox.StandardButton.Yes)
        msgbox.addButton(QMessageBox.StandardButton.No)
        msgbox.setDefaultButton(QMessageBox.StandardButton.No)
        reply = msgbox.exec()
        if reply == QMessageBox.StandardButton.No:
            return

        self.installPlugin(url, "update")

    def installPlugin(self, url, action_type="update"):
        save_path = tempfile.gettempdir() + os.sep + "layman.zip"
        self.download_url(url, save_path)

        with ZipFile(save_path, "r") as zipObj:
            zipObj.extractall(tempfile.gettempdir())

        if "master.zip" in url:
            extracted_dir = "qgis-layman-plugin-master"
        elif "3.x.zip" in url:
            extracted_dir = "qgis-layman-plugin-3.x"
        else:
            temp_dir = tempfile.gettempdir()
            for item in os.listdir(temp_dir):
                if item.startswith("qgis-layman-plugin-"):
                    extracted_dir = item
                    break
            else:
                self.utils.emitMessageBox.emit(
                    [
                        self.tr("Plugin was not updated!"),
                        self.tr("Could not find extracted plugin directory"),
                    ]
                )
                return

        src = tempfile.gettempdir() + os.sep + extracted_dir

        if not self.copytree(src, self.layman.plugin_dir):
            return

        self.close()
        self.layman.disableEnvironment()

        if action_type == "downgrade":
            message = self.tr(
                "Layman plugin was downgraded to version 2.x. Please restart QGIS."
            )
        elif action_type == "upgrade":
            message = self.tr(
                "Layman plugin was upgraded to version 3.x. Please restart QGIS."
            )
        else:
            message = self.tr("Layman plugin was updated. Please restart QGIS.")

        QMessageBox.information(None, self.tr("Layman"), message)

    def copytree(self, src, dst, symlinks=False, ignore=None):
        try:
            shutil.rmtree(dst)
            os.mkdir(dst)
        except Exception as e:
            self.utils.emitMessageBox.emit(
                [self.tr("Plugin was not updated!"), self.tr("Plugin was not updated!")]
            )
            return False
        for item in os.listdir(src):
            s = os.path.join(src, item)
            d = os.path.join(dst, item)
            if os.path.isdir(s):
                shutil.copytree(s, d, symlinks, ignore)
            else:
                shutil.copy2(s, d)
        return True

    def download_url(self, url, save_path, chunk_size=128):
        r = requests.get(url, stream=True)
        with open(save_path, "wb") as fd:
            for chunk in r.iter_content(chunk_size=chunk_size):
                fd.write(chunk)

    def checkVersionForBranch(self, branch):
        """Check version availability for specific branch"""
        if branch == "3.x":
            url = "https://raw.githubusercontent.com/LESPROJEKT/qgis-layman-plugin/3.x/metadata.txt"
        else:  # master
            url = "https://raw.githubusercontent.com/LESPROJEKT/qgis-layman-plugin/master/metadata.txt"

        try:
            r = requests.get(url)
            buf = io.StringIO(r.text)
            config = configparser.ConfigParser()
            config.read_file(buf)
            version = config.get("general", "version")
            installedVersion = self.utils.getVersion()
            if installedVersion == version:
                return [True, version]
            else:
                return [False, version]
        except Exception as e:
            # If we can't check the version, assume update is available
            return [False, "Unknown"]

    def checkQgisVersion(self):
        version = Qgis.QGIS_VERSION_INT
        major = version // 10000
        minor = (version // 100) % 100
        if major > 3 or (major == 3 and minor >= 26):
            return True
        else:
            return False

    def delete_whole_user(self):
        reply = QMessageBox.question(
            None,
            self.tr("Confirm Deletion"),
            self.tr(
                "Are you sure you want to delete all your publications and your account?"
            ),
            QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No,
            QMessageBox.StandardButton.No,
        )

        if reply == QMessageBox.StandardButton.Yes:
            url = self.layman_api.get_user_delete_url(self.laymanUsername)
            response = requests.delete(url)
            if response.status_code == 200:
                QMessageBox.information(
                    None,
                    self.tr("Account Deleted"),
                    self.tr(
                        "Your account and all publications have been successfully deleted."
                    ),
                )
                return
            else:
                try:
                    error_data = response.json()
                    error_code = error_data.get("code", None)
                    if error_code == 58:
                        unable_delete = error_data.get(
                            "unable_to_delete_publications", []
                        )
                        pub_list_str = "\n".join(
                            f"- {pub.get('name')} (workspace: {pub.get('workspace')}, type: {pub.get('type')})"
                            for pub in unable_delete
                        )
                        QMessageBox.warning(
                            None,
                            self.tr("Deletion Error"),
                            self.tr(
                                "Your account cannot be deleted because the following publications "
                                "are shared with other readers:\n\n"
                                f"{pub_list_str}\n\n"
                                "Please remove or update permissions before deleting your account."
                            ),
                        )
                    else:
                        QMessageBox.critical(
                            None,
                            self.tr("Deletion Error"),
                            self.tr(
                                f"An error occurred while deleting your account.\n\n"
                                f"Server returned status code: {response.status_code}\n"
                                f"Details: {error_data}"
                            ),
                        )

                except ValueError:
                    QMessageBox.critical(
                        None,
                        self.tr("Deletion Error"),
                        self.tr(
                            f"An unexpected error occurred. Response text:\n{response.text}"
                        ),
                    )
        else:
            print("User canceled deletion.")
